/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PendingApprovalRouteImport } from './routes/pending-approval'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as ApplicationRejectedRouteImport } from './routes/application-rejected'
import { Route as WorkerRouteRouteImport } from './routes/_worker/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as WorkerWorkerIndexRouteImport } from './routes/_worker/worker/index'
import { Route as AuthenticatedWorkersIndexRouteImport } from './routes/_authenticated/workers.index'
import { Route as AuthenticatedToolsIndexRouteImport } from './routes/_authenticated/tools.index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports.index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance.index'
import { Route as AuthenticatedEstimatesIndexRouteImport } from './routes/_authenticated/estimates.index'
import { Route as AuthenticatedActivityIndexRouteImport } from './routes/_authenticated/activity.index'
import { Route as WorkerWorkerReportsRouteImport } from './routes/_worker/worker/reports'
import { Route as WorkerWorkerProjectsRouteImport } from './routes/_worker/worker/projects'
import { Route as WorkerWorkerProfileRouteImport } from './routes/_worker/worker/profile'
import { Route as WorkerWorkerNotificationsRouteImport } from './routes/_worker/worker/notifications'
import { Route as WorkerWorkerFinanceRouteImport } from './routes/_worker/worker/finance'
import { Route as WorkerWorkerDocumentsRouteImport } from './routes/_worker/worker/documents'
import { Route as AuthenticatedWorkersWorkerIdRouteImport } from './routes/_authenticated/workers.$workerId'
import { Route as AuthenticatedToolsToolIdRouteImport } from './routes/_authenticated/tools.$toolId'
import { Route as AuthenticatedReportsReportIdRouteImport } from './routes/_authenticated/reports.$reportId'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedEstimatesEstimateIdRouteImport } from './routes/_authenticated/estimates.$estimateId'
import { Route as AuthenticatedDailyReportsDailyIdRouteImport } from './routes/_authenticated/daily-reports.$dailyId'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients.$clientId'
import { Route as WorkerWorkerReportsIndexRouteImport } from './routes/_worker/worker/reports.index'
import { Route as WorkerWorkerProjectsIndexRouteImport } from './routes/_worker/worker/projects.index'
import { Route as WorkerWorkerReportsNewRouteImport } from './routes/_worker/worker/reports.new'
import { Route as WorkerWorkerReportsReportIdRouteImport } from './routes/_worker/worker/reports.$reportId'
import { Route as WorkerWorkerProjectsProjectIdRouteImport } from './routes/_worker/worker/projects.$projectId'
import { Route as WorkerWorkerDailyReportsNewRouteImport } from './routes/_worker/worker/daily-reports.new'
import { Route as WorkerWorkerDailyReportsDailyIdRouteImport } from './routes/_worker/worker/daily-reports.$dailyId'
import { Route as WorkerWorkerProjectsProjectIdIndexRouteImport } from './routes/_worker/worker/projects.$projectId.index'
import { Route as WorkerWorkerProjectsProjectIdToolsRouteImport } from './routes/_worker/worker/projects.$projectId.tools'
import { Route as WorkerWorkerProjectsProjectIdTeamRouteImport } from './routes/_worker/worker/projects.$projectId.team'

const PendingApprovalRoute = PendingApprovalRouteImport.update({
  id: '/pending-approval',
  path: '/pending-approval',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationRejectedRoute = ApplicationRejectedRouteImport.update({
  id: '/application-rejected',
  path: '/application-rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerRouteRoute = WorkerRouteRouteImport.update({
  id: '/_worker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerWorkerIndexRoute = WorkerWorkerIndexRouteImport.update({
  id: '/worker/',
  path: '/worker/',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const AuthenticatedWorkersIndexRoute =
  AuthenticatedWorkersIndexRouteImport.update({
    id: '/workers/',
    path: '/workers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsIndexRoute = AuthenticatedToolsIndexRouteImport.update({
  id: '/tools/',
  path: '/tools/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstimatesIndexRoute =
  AuthenticatedEstimatesIndexRouteImport.update({
    id: '/estimates/',
    path: '/estimates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedActivityIndexRoute =
  AuthenticatedActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WorkerWorkerReportsRoute = WorkerWorkerReportsRouteImport.update({
  id: '/worker/reports',
  path: '/worker/reports',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerWorkerProjectsRoute = WorkerWorkerProjectsRouteImport.update({
  id: '/worker/projects',
  path: '/worker/projects',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerWorkerProfileRoute = WorkerWorkerProfileRouteImport.update({
  id: '/worker/profile',
  path: '/worker/profile',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerWorkerNotificationsRoute =
  WorkerWorkerNotificationsRouteImport.update({
    id: '/worker/notifications',
    path: '/worker/notifications',
    getParentRoute: () => WorkerRouteRoute,
  } as any)
const WorkerWorkerFinanceRoute = WorkerWorkerFinanceRouteImport.update({
  id: '/worker/finance',
  path: '/worker/finance',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const WorkerWorkerDocumentsRoute = WorkerWorkerDocumentsRouteImport.update({
  id: '/worker/documents',
  path: '/worker/documents',
  getParentRoute: () => WorkerRouteRoute,
} as any)
const AuthenticatedWorkersWorkerIdRoute =
  AuthenticatedWorkersWorkerIdRouteImport.update({
    id: '/workers/$workerId',
    path: '/workers/$workerId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsToolIdRoute =
  AuthenticatedToolsToolIdRouteImport.update({
    id: '/tools/$toolId',
    path: '/tools/$toolId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsReportIdRoute =
  AuthenticatedReportsReportIdRouteImport.update({
    id: '/reports/$reportId',
    path: '/reports/$reportId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEstimatesEstimateIdRoute =
  AuthenticatedEstimatesEstimateIdRouteImport.update({
    id: '/estimates/$estimateId',
    path: '/estimates/$estimateId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDailyReportsDailyIdRoute =
  AuthenticatedDailyReportsDailyIdRouteImport.update({
    id: '/daily-reports/$dailyId',
    path: '/daily-reports/$dailyId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const WorkerWorkerReportsIndexRoute =
  WorkerWorkerReportsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkerWorkerReportsRoute,
  } as any)
const WorkerWorkerProjectsIndexRoute =
  WorkerWorkerProjectsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkerWorkerProjectsRoute,
  } as any)
const WorkerWorkerReportsNewRoute = WorkerWorkerReportsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkerWorkerReportsRoute,
} as any)
const WorkerWorkerReportsReportIdRoute =
  WorkerWorkerReportsReportIdRouteImport.update({
    id: '/$reportId',
    path: '/$reportId',
    getParentRoute: () => WorkerWorkerReportsRoute,
  } as any)
const WorkerWorkerProjectsProjectIdRoute =
  WorkerWorkerProjectsProjectIdRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => WorkerWorkerProjectsRoute,
  } as any)
const WorkerWorkerDailyReportsNewRoute =
  WorkerWorkerDailyReportsNewRouteImport.update({
    id: '/worker/daily-reports/new',
    path: '/worker/daily-reports/new',
    getParentRoute: () => WorkerRouteRoute,
  } as any)
const WorkerWorkerDailyReportsDailyIdRoute =
  WorkerWorkerDailyReportsDailyIdRouteImport.update({
    id: '/worker/daily-reports/$dailyId',
    path: '/worker/daily-reports/$dailyId',
    getParentRoute: () => WorkerRouteRoute,
  } as any)
const WorkerWorkerProjectsProjectIdIndexRoute =
  WorkerWorkerProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => WorkerWorkerProjectsProjectIdRoute,
  } as any)
const WorkerWorkerProjectsProjectIdToolsRoute =
  WorkerWorkerProjectsProjectIdToolsRouteImport.update({
    id: '/tools',
    path: '/tools',
    getParentRoute: () => WorkerWorkerProjectsProjectIdRoute,
  } as any)
const WorkerWorkerProjectsProjectIdTeamRoute =
  WorkerWorkerProjectsProjectIdTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => WorkerWorkerProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/application-rejected': typeof ApplicationRejectedRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/daily-reports/$dailyId': typeof AuthenticatedDailyReportsDailyIdRoute
  '/estimates/$estimateId': typeof AuthenticatedEstimatesEstimateIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/tools/$toolId': typeof AuthenticatedToolsToolIdRoute
  '/workers/$workerId': typeof AuthenticatedWorkersWorkerIdRoute
  '/worker/documents': typeof WorkerWorkerDocumentsRoute
  '/worker/finance': typeof WorkerWorkerFinanceRoute
  '/worker/notifications': typeof WorkerWorkerNotificationsRoute
  '/worker/profile': typeof WorkerWorkerProfileRoute
  '/worker/projects': typeof WorkerWorkerProjectsRouteWithChildren
  '/worker/reports': typeof WorkerWorkerReportsRouteWithChildren
  '/activity/': typeof AuthenticatedActivityIndexRoute
  '/estimates/': typeof AuthenticatedEstimatesIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/tools/': typeof AuthenticatedToolsIndexRoute
  '/workers/': typeof AuthenticatedWorkersIndexRoute
  '/worker/': typeof WorkerWorkerIndexRoute
  '/worker/daily-reports/$dailyId': typeof WorkerWorkerDailyReportsDailyIdRoute
  '/worker/daily-reports/new': typeof WorkerWorkerDailyReportsNewRoute
  '/worker/projects/$projectId': typeof WorkerWorkerProjectsProjectIdRouteWithChildren
  '/worker/reports/$reportId': typeof WorkerWorkerReportsReportIdRoute
  '/worker/reports/new': typeof WorkerWorkerReportsNewRoute
  '/worker/projects/': typeof WorkerWorkerProjectsIndexRoute
  '/worker/reports/': typeof WorkerWorkerReportsIndexRoute
  '/worker/projects/$projectId/team': typeof WorkerWorkerProjectsProjectIdTeamRoute
  '/worker/projects/$projectId/tools': typeof WorkerWorkerProjectsProjectIdToolsRoute
  '/worker/projects/$projectId/': typeof WorkerWorkerProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedIndexRoute
  '/application-rejected': typeof ApplicationRejectedRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/daily-reports/$dailyId': typeof AuthenticatedDailyReportsDailyIdRoute
  '/estimates/$estimateId': typeof AuthenticatedEstimatesEstimateIdRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/tools/$toolId': typeof AuthenticatedToolsToolIdRoute
  '/workers/$workerId': typeof AuthenticatedWorkersWorkerIdRoute
  '/worker/documents': typeof WorkerWorkerDocumentsRoute
  '/worker/finance': typeof WorkerWorkerFinanceRoute
  '/worker/notifications': typeof WorkerWorkerNotificationsRoute
  '/worker/profile': typeof WorkerWorkerProfileRoute
  '/activity': typeof AuthenticatedActivityIndexRoute
  '/estimates': typeof AuthenticatedEstimatesIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/tools': typeof AuthenticatedToolsIndexRoute
  '/workers': typeof AuthenticatedWorkersIndexRoute
  '/worker': typeof WorkerWorkerIndexRoute
  '/worker/daily-reports/$dailyId': typeof WorkerWorkerDailyReportsDailyIdRoute
  '/worker/daily-reports/new': typeof WorkerWorkerDailyReportsNewRoute
  '/worker/reports/$reportId': typeof WorkerWorkerReportsReportIdRoute
  '/worker/reports/new': typeof WorkerWorkerReportsNewRoute
  '/worker/projects': typeof WorkerWorkerProjectsIndexRoute
  '/worker/reports': typeof WorkerWorkerReportsIndexRoute
  '/worker/projects/$projectId/team': typeof WorkerWorkerProjectsProjectIdTeamRoute
  '/worker/projects/$projectId/tools': typeof WorkerWorkerProjectsProjectIdToolsRoute
  '/worker/projects/$projectId': typeof WorkerWorkerProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_worker': typeof WorkerRouteRouteWithChildren
  '/application-rejected': typeof ApplicationRejectedRoute
  '/logout': typeof LogoutRoute
  '/onboarding': typeof OnboardingRoute
  '/pending-approval': typeof PendingApprovalRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/daily-reports/$dailyId': typeof AuthenticatedDailyReportsDailyIdRoute
  '/_authenticated/estimates/$estimateId': typeof AuthenticatedEstimatesEstimateIdRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/reports/$reportId': typeof AuthenticatedReportsReportIdRoute
  '/_authenticated/tools/$toolId': typeof AuthenticatedToolsToolIdRoute
  '/_authenticated/workers/$workerId': typeof AuthenticatedWorkersWorkerIdRoute
  '/_worker/worker/documents': typeof WorkerWorkerDocumentsRoute
  '/_worker/worker/finance': typeof WorkerWorkerFinanceRoute
  '/_worker/worker/notifications': typeof WorkerWorkerNotificationsRoute
  '/_worker/worker/profile': typeof WorkerWorkerProfileRoute
  '/_worker/worker/projects': typeof WorkerWorkerProjectsRouteWithChildren
  '/_worker/worker/reports': typeof WorkerWorkerReportsRouteWithChildren
  '/_authenticated/activity/': typeof AuthenticatedActivityIndexRoute
  '/_authenticated/estimates/': typeof AuthenticatedEstimatesIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/tools/': typeof AuthenticatedToolsIndexRoute
  '/_authenticated/workers/': typeof AuthenticatedWorkersIndexRoute
  '/_worker/worker/': typeof WorkerWorkerIndexRoute
  '/_worker/worker/daily-reports/$dailyId': typeof WorkerWorkerDailyReportsDailyIdRoute
  '/_worker/worker/daily-reports/new': typeof WorkerWorkerDailyReportsNewRoute
  '/_worker/worker/projects/$projectId': typeof WorkerWorkerProjectsProjectIdRouteWithChildren
  '/_worker/worker/reports/$reportId': typeof WorkerWorkerReportsReportIdRoute
  '/_worker/worker/reports/new': typeof WorkerWorkerReportsNewRoute
  '/_worker/worker/projects/': typeof WorkerWorkerProjectsIndexRoute
  '/_worker/worker/reports/': typeof WorkerWorkerReportsIndexRoute
  '/_worker/worker/projects/$projectId/team': typeof WorkerWorkerProjectsProjectIdTeamRoute
  '/_worker/worker/projects/$projectId/tools': typeof WorkerWorkerProjectsProjectIdToolsRoute
  '/_worker/worker/projects/$projectId/': typeof WorkerWorkerProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/application-rejected'
    | '/logout'
    | '/onboarding'
    | '/pending-approval'
    | '/auth/login'
    | '/auth/register'
    | '/clients/$clientId'
    | '/daily-reports/$dailyId'
    | '/estimates/$estimateId'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/tools/$toolId'
    | '/workers/$workerId'
    | '/worker/documents'
    | '/worker/finance'
    | '/worker/notifications'
    | '/worker/profile'
    | '/worker/projects'
    | '/worker/reports'
    | '/activity/'
    | '/estimates/'
    | '/finance/'
    | '/projects/'
    | '/reports/'
    | '/tools/'
    | '/workers/'
    | '/worker/'
    | '/worker/daily-reports/$dailyId'
    | '/worker/daily-reports/new'
    | '/worker/projects/$projectId'
    | '/worker/reports/$reportId'
    | '/worker/reports/new'
    | '/worker/projects/'
    | '/worker/reports/'
    | '/worker/projects/$projectId/team'
    | '/worker/projects/$projectId/tools'
    | '/worker/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/application-rejected'
    | '/logout'
    | '/onboarding'
    | '/pending-approval'
    | '/auth/login'
    | '/auth/register'
    | '/clients/$clientId'
    | '/daily-reports/$dailyId'
    | '/estimates/$estimateId'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/tools/$toolId'
    | '/workers/$workerId'
    | '/worker/documents'
    | '/worker/finance'
    | '/worker/notifications'
    | '/worker/profile'
    | '/activity'
    | '/estimates'
    | '/finance'
    | '/projects'
    | '/reports'
    | '/tools'
    | '/workers'
    | '/worker'
    | '/worker/daily-reports/$dailyId'
    | '/worker/daily-reports/new'
    | '/worker/reports/$reportId'
    | '/worker/reports/new'
    | '/worker/projects'
    | '/worker/reports'
    | '/worker/projects/$projectId/team'
    | '/worker/projects/$projectId/tools'
    | '/worker/projects/$projectId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_worker'
    | '/application-rejected'
    | '/logout'
    | '/onboarding'
    | '/pending-approval'
    | '/auth/login'
    | '/auth/register'
    | '/_authenticated/'
    | '/_authenticated/clients/$clientId'
    | '/_authenticated/daily-reports/$dailyId'
    | '/_authenticated/estimates/$estimateId'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/reports/$reportId'
    | '/_authenticated/tools/$toolId'
    | '/_authenticated/workers/$workerId'
    | '/_worker/worker/documents'
    | '/_worker/worker/finance'
    | '/_worker/worker/notifications'
    | '/_worker/worker/profile'
    | '/_worker/worker/projects'
    | '/_worker/worker/reports'
    | '/_authenticated/activity/'
    | '/_authenticated/estimates/'
    | '/_authenticated/finance/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/tools/'
    | '/_authenticated/workers/'
    | '/_worker/worker/'
    | '/_worker/worker/daily-reports/$dailyId'
    | '/_worker/worker/daily-reports/new'
    | '/_worker/worker/projects/$projectId'
    | '/_worker/worker/reports/$reportId'
    | '/_worker/worker/reports/new'
    | '/_worker/worker/projects/'
    | '/_worker/worker/reports/'
    | '/_worker/worker/projects/$projectId/team'
    | '/_worker/worker/projects/$projectId/tools'
    | '/_worker/worker/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  WorkerRouteRoute: typeof WorkerRouteRouteWithChildren
  ApplicationRejectedRoute: typeof ApplicationRejectedRoute
  LogoutRoute: typeof LogoutRoute
  OnboardingRoute: typeof OnboardingRoute
  PendingApprovalRoute: typeof PendingApprovalRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pending-approval': {
      id: '/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof PendingApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/application-rejected': {
      id: '/application-rejected'
      path: '/application-rejected'
      fullPath: '/application-rejected'
      preLoaderRoute: typeof ApplicationRejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_worker': {
      id: '/_worker'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_worker/worker/': {
      id: '/_worker/worker/'
      path: '/worker'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerWorkerIndexRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_authenticated/workers/': {
      id: '/_authenticated/workers/'
      path: '/workers'
      fullPath: '/workers/'
      preLoaderRoute: typeof AuthenticatedWorkersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/': {
      id: '/_authenticated/tools/'
      path: '/tools'
      fullPath: '/tools/'
      preLoaderRoute: typeof AuthenticatedToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates/': {
      id: '/_authenticated/estimates/'
      path: '/estimates'
      fullPath: '/estimates/'
      preLoaderRoute: typeof AuthenticatedEstimatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity/': {
      id: '/_authenticated/activity/'
      path: '/activity'
      fullPath: '/activity/'
      preLoaderRoute: typeof AuthenticatedActivityIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_worker/worker/reports': {
      id: '/_worker/worker/reports'
      path: '/worker/reports'
      fullPath: '/worker/reports'
      preLoaderRoute: typeof WorkerWorkerReportsRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/projects': {
      id: '/_worker/worker/projects'
      path: '/worker/projects'
      fullPath: '/worker/projects'
      preLoaderRoute: typeof WorkerWorkerProjectsRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/profile': {
      id: '/_worker/worker/profile'
      path: '/worker/profile'
      fullPath: '/worker/profile'
      preLoaderRoute: typeof WorkerWorkerProfileRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/notifications': {
      id: '/_worker/worker/notifications'
      path: '/worker/notifications'
      fullPath: '/worker/notifications'
      preLoaderRoute: typeof WorkerWorkerNotificationsRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/finance': {
      id: '/_worker/worker/finance'
      path: '/worker/finance'
      fullPath: '/worker/finance'
      preLoaderRoute: typeof WorkerWorkerFinanceRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/documents': {
      id: '/_worker/worker/documents'
      path: '/worker/documents'
      fullPath: '/worker/documents'
      preLoaderRoute: typeof WorkerWorkerDocumentsRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_authenticated/workers/$workerId': {
      id: '/_authenticated/workers/$workerId'
      path: '/workers/$workerId'
      fullPath: '/workers/$workerId'
      preLoaderRoute: typeof AuthenticatedWorkersWorkerIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools/$toolId': {
      id: '/_authenticated/tools/$toolId'
      path: '/tools/$toolId'
      fullPath: '/tools/$toolId'
      preLoaderRoute: typeof AuthenticatedToolsToolIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$reportId': {
      id: '/_authenticated/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AuthenticatedReportsReportIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/estimates/$estimateId': {
      id: '/_authenticated/estimates/$estimateId'
      path: '/estimates/$estimateId'
      fullPath: '/estimates/$estimateId'
      preLoaderRoute: typeof AuthenticatedEstimatesEstimateIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily-reports/$dailyId': {
      id: '/_authenticated/daily-reports/$dailyId'
      path: '/daily-reports/$dailyId'
      fullPath: '/daily-reports/$dailyId'
      preLoaderRoute: typeof AuthenticatedDailyReportsDailyIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_worker/worker/reports/': {
      id: '/_worker/worker/reports/'
      path: '/'
      fullPath: '/worker/reports/'
      preLoaderRoute: typeof WorkerWorkerReportsIndexRouteImport
      parentRoute: typeof WorkerWorkerReportsRoute
    }
    '/_worker/worker/projects/': {
      id: '/_worker/worker/projects/'
      path: '/'
      fullPath: '/worker/projects/'
      preLoaderRoute: typeof WorkerWorkerProjectsIndexRouteImport
      parentRoute: typeof WorkerWorkerProjectsRoute
    }
    '/_worker/worker/reports/new': {
      id: '/_worker/worker/reports/new'
      path: '/new'
      fullPath: '/worker/reports/new'
      preLoaderRoute: typeof WorkerWorkerReportsNewRouteImport
      parentRoute: typeof WorkerWorkerReportsRoute
    }
    '/_worker/worker/reports/$reportId': {
      id: '/_worker/worker/reports/$reportId'
      path: '/$reportId'
      fullPath: '/worker/reports/$reportId'
      preLoaderRoute: typeof WorkerWorkerReportsReportIdRouteImport
      parentRoute: typeof WorkerWorkerReportsRoute
    }
    '/_worker/worker/projects/$projectId': {
      id: '/_worker/worker/projects/$projectId'
      path: '/$projectId'
      fullPath: '/worker/projects/$projectId'
      preLoaderRoute: typeof WorkerWorkerProjectsProjectIdRouteImport
      parentRoute: typeof WorkerWorkerProjectsRoute
    }
    '/_worker/worker/daily-reports/new': {
      id: '/_worker/worker/daily-reports/new'
      path: '/worker/daily-reports/new'
      fullPath: '/worker/daily-reports/new'
      preLoaderRoute: typeof WorkerWorkerDailyReportsNewRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/daily-reports/$dailyId': {
      id: '/_worker/worker/daily-reports/$dailyId'
      path: '/worker/daily-reports/$dailyId'
      fullPath: '/worker/daily-reports/$dailyId'
      preLoaderRoute: typeof WorkerWorkerDailyReportsDailyIdRouteImport
      parentRoute: typeof WorkerRouteRoute
    }
    '/_worker/worker/projects/$projectId/': {
      id: '/_worker/worker/projects/$projectId/'
      path: '/'
      fullPath: '/worker/projects/$projectId/'
      preLoaderRoute: typeof WorkerWorkerProjectsProjectIdIndexRouteImport
      parentRoute: typeof WorkerWorkerProjectsProjectIdRoute
    }
    '/_worker/worker/projects/$projectId/tools': {
      id: '/_worker/worker/projects/$projectId/tools'
      path: '/tools'
      fullPath: '/worker/projects/$projectId/tools'
      preLoaderRoute: typeof WorkerWorkerProjectsProjectIdToolsRouteImport
      parentRoute: typeof WorkerWorkerProjectsProjectIdRoute
    }
    '/_worker/worker/projects/$projectId/team': {
      id: '/_worker/worker/projects/$projectId/team'
      path: '/team'
      fullPath: '/worker/projects/$projectId/team'
      preLoaderRoute: typeof WorkerWorkerProjectsProjectIdTeamRouteImport
      parentRoute: typeof WorkerWorkerProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedDailyReportsDailyIdRoute: typeof AuthenticatedDailyReportsDailyIdRoute
  AuthenticatedEstimatesEstimateIdRoute: typeof AuthenticatedEstimatesEstimateIdRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedReportsReportIdRoute: typeof AuthenticatedReportsReportIdRoute
  AuthenticatedToolsToolIdRoute: typeof AuthenticatedToolsToolIdRoute
  AuthenticatedWorkersWorkerIdRoute: typeof AuthenticatedWorkersWorkerIdRoute
  AuthenticatedActivityIndexRoute: typeof AuthenticatedActivityIndexRoute
  AuthenticatedEstimatesIndexRoute: typeof AuthenticatedEstimatesIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedToolsIndexRoute: typeof AuthenticatedToolsIndexRoute
  AuthenticatedWorkersIndexRoute: typeof AuthenticatedWorkersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedDailyReportsDailyIdRoute: AuthenticatedDailyReportsDailyIdRoute,
  AuthenticatedEstimatesEstimateIdRoute: AuthenticatedEstimatesEstimateIdRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedReportsReportIdRoute: AuthenticatedReportsReportIdRoute,
  AuthenticatedToolsToolIdRoute: AuthenticatedToolsToolIdRoute,
  AuthenticatedWorkersWorkerIdRoute: AuthenticatedWorkersWorkerIdRoute,
  AuthenticatedActivityIndexRoute: AuthenticatedActivityIndexRoute,
  AuthenticatedEstimatesIndexRoute: AuthenticatedEstimatesIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedToolsIndexRoute: AuthenticatedToolsIndexRoute,
  AuthenticatedWorkersIndexRoute: AuthenticatedWorkersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface WorkerWorkerProjectsProjectIdRouteChildren {
  WorkerWorkerProjectsProjectIdTeamRoute: typeof WorkerWorkerProjectsProjectIdTeamRoute
  WorkerWorkerProjectsProjectIdToolsRoute: typeof WorkerWorkerProjectsProjectIdToolsRoute
  WorkerWorkerProjectsProjectIdIndexRoute: typeof WorkerWorkerProjectsProjectIdIndexRoute
}

const WorkerWorkerProjectsProjectIdRouteChildren: WorkerWorkerProjectsProjectIdRouteChildren =
  {
    WorkerWorkerProjectsProjectIdTeamRoute:
      WorkerWorkerProjectsProjectIdTeamRoute,
    WorkerWorkerProjectsProjectIdToolsRoute:
      WorkerWorkerProjectsProjectIdToolsRoute,
    WorkerWorkerProjectsProjectIdIndexRoute:
      WorkerWorkerProjectsProjectIdIndexRoute,
  }

const WorkerWorkerProjectsProjectIdRouteWithChildren =
  WorkerWorkerProjectsProjectIdRoute._addFileChildren(
    WorkerWorkerProjectsProjectIdRouteChildren,
  )

interface WorkerWorkerProjectsRouteChildren {
  WorkerWorkerProjectsProjectIdRoute: typeof WorkerWorkerProjectsProjectIdRouteWithChildren
  WorkerWorkerProjectsIndexRoute: typeof WorkerWorkerProjectsIndexRoute
}

const WorkerWorkerProjectsRouteChildren: WorkerWorkerProjectsRouteChildren = {
  WorkerWorkerProjectsProjectIdRoute:
    WorkerWorkerProjectsProjectIdRouteWithChildren,
  WorkerWorkerProjectsIndexRoute: WorkerWorkerProjectsIndexRoute,
}

const WorkerWorkerProjectsRouteWithChildren =
  WorkerWorkerProjectsRoute._addFileChildren(WorkerWorkerProjectsRouteChildren)

interface WorkerWorkerReportsRouteChildren {
  WorkerWorkerReportsReportIdRoute: typeof WorkerWorkerReportsReportIdRoute
  WorkerWorkerReportsNewRoute: typeof WorkerWorkerReportsNewRoute
  WorkerWorkerReportsIndexRoute: typeof WorkerWorkerReportsIndexRoute
}

const WorkerWorkerReportsRouteChildren: WorkerWorkerReportsRouteChildren = {
  WorkerWorkerReportsReportIdRoute: WorkerWorkerReportsReportIdRoute,
  WorkerWorkerReportsNewRoute: WorkerWorkerReportsNewRoute,
  WorkerWorkerReportsIndexRoute: WorkerWorkerReportsIndexRoute,
}

const WorkerWorkerReportsRouteWithChildren =
  WorkerWorkerReportsRoute._addFileChildren(WorkerWorkerReportsRouteChildren)

interface WorkerRouteRouteChildren {
  WorkerWorkerDocumentsRoute: typeof WorkerWorkerDocumentsRoute
  WorkerWorkerFinanceRoute: typeof WorkerWorkerFinanceRoute
  WorkerWorkerNotificationsRoute: typeof WorkerWorkerNotificationsRoute
  WorkerWorkerProfileRoute: typeof WorkerWorkerProfileRoute
  WorkerWorkerProjectsRoute: typeof WorkerWorkerProjectsRouteWithChildren
  WorkerWorkerReportsRoute: typeof WorkerWorkerReportsRouteWithChildren
  WorkerWorkerIndexRoute: typeof WorkerWorkerIndexRoute
  WorkerWorkerDailyReportsDailyIdRoute: typeof WorkerWorkerDailyReportsDailyIdRoute
  WorkerWorkerDailyReportsNewRoute: typeof WorkerWorkerDailyReportsNewRoute
}

const WorkerRouteRouteChildren: WorkerRouteRouteChildren = {
  WorkerWorkerDocumentsRoute: WorkerWorkerDocumentsRoute,
  WorkerWorkerFinanceRoute: WorkerWorkerFinanceRoute,
  WorkerWorkerNotificationsRoute: WorkerWorkerNotificationsRoute,
  WorkerWorkerProfileRoute: WorkerWorkerProfileRoute,
  WorkerWorkerProjectsRoute: WorkerWorkerProjectsRouteWithChildren,
  WorkerWorkerReportsRoute: WorkerWorkerReportsRouteWithChildren,
  WorkerWorkerIndexRoute: WorkerWorkerIndexRoute,
  WorkerWorkerDailyReportsDailyIdRoute: WorkerWorkerDailyReportsDailyIdRoute,
  WorkerWorkerDailyReportsNewRoute: WorkerWorkerDailyReportsNewRoute,
}

const WorkerRouteRouteWithChildren = WorkerRouteRoute._addFileChildren(
  WorkerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  WorkerRouteRoute: WorkerRouteRouteWithChildren,
  ApplicationRejectedRoute: ApplicationRejectedRoute,
  LogoutRoute: LogoutRoute,
  OnboardingRoute: OnboardingRoute,
  PendingApprovalRoute: PendingApprovalRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
