root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ./cmd/server"
  bin = "tmp/main"
  full_bin = "tmp/main"
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "testdata", "migrations"]
  delay = 1000
  stop_on_error = true

[log]
  time = true

[misc]
  clean_on_exit = true
